# This is a bit complex with multiple jobs.
# https://circleci.com/docs/2.0/local-cli/ will let you test this locally
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12
    environment:
      GO111MODULE=on
    working_directory: ~/iavl
    steps:
      - checkout
      - run: make build
      - run: make test
